"""
IFCT 2017 Indian Food & Recipe Nutrition Seeder.
Populates standard cooked dish profiles grounded in ICMR-NIN Indian Food Composition Tables
for all 50 core Indian cuisine classes.
"""
import asyncio
import logging
from sqlalchemy import select
from db.connection import AsyncSessionLocal, init_db
from db.models import DishNutritionProfile

logger = logging.getLogger(__name__)

# ICMR-NIN IFCT 2017 grounded nutrition profiles (Values per 100g of prepared dish)
SEEDED_INDIAN_DISHES = [
    # --- DALS, PULSES & LEGUMES ---
    {
        "dish_key": "besan_cheela",
        "display_name": "Besan Cheela (Savory Gram Flour Pancake)",
        "category": "Breakfast",
        "default_serving_grams": 100.0,
        "calories_per_100g": 195.0,
        "protein_per_100g": 8.5,
        "carbs_per_100g": 24.0,
        "fat_per_100g": 7.2,
        "fiber_per_100g": 4.2,
        "iron_mg_per_100g": 2.5,
        "calcium_mg_per_100g": 40.0,
        "vitamin_c_mg_per_100g": 4.5,
        "vitamin_a_ug_per_100g": 15.0,
        "sodium_mg_per_100g": 260.0,
        "aliases": "cheela, besan chilla, gram flour pancake, savory pancake, besan puda",
    },
    {
        "dish_key": "rolls",
        "display_name": "Paneer / Chicken Kathi Roll",
        "category": "Snack",
        "default_serving_grams": 150.0,
        "calories_per_100g": 230.0,
        "protein_per_100g": 9.8,
        "carbs_per_100g": 26.5,
        "fat_per_100g": 9.5,
        "fiber_per_100g": 2.4,
        "iron_mg_per_100g": 1.9,
        "calcium_mg_per_100g": 55.0,
        "vitamin_c_mg_per_100g": 5.2,
        "vitamin_a_ug_per_100g": 40.0,
        "sodium_mg_per_100g": 360.0,
        "aliases": "kathi roll, frankie, paneer roll, chicken roll, egg roll, wrap",
    },
    {
        "dish_key": "dal_tadka",
        "display_name": "Dal Tadka (Yellow Lentil Tempered)",
        "category": "Dal",
        "default_serving_grams": 150.0,
        "calories_per_100g": 105.0,
        "protein_per_100g": 5.2,
        "carbs_per_100g": 13.5,
        "fat_per_100g": 3.6,
        "fiber_per_100g": 3.1,
        "iron_mg_per_100g": 1.4,
        "calcium_mg_per_100g": 24.0,
        "vitamin_c_mg_per_100g": 2.5,
        "vitamin_a_ug_per_100g": 18.0,
        "sodium_mg_per_100g": 220.0,
        "aliases": "dal, yellow dal, toor dal, arhar dal, dal fry, tadka dal, peeli dal, cooked dal, yellow dal fry",
    },
    {
        "dish_key": "dal_makhani",
        "display_name": "Dal Makhani (Black Lentil & Butter)",
        "category": "Dal",
        "default_serving_grams": 150.0,
        "calories_per_100g": 145.0,
        "protein_per_100g": 5.8,
        "carbs_per_100g": 14.2,
        "fat_per_100g": 7.5,
        "fiber_per_100g": 3.8,
        "iron_mg_per_100g": 1.8,
        "calcium_mg_per_100g": 45.0,
        "vitamin_c_mg_per_100g": 1.2,
        "vitamin_a_ug_per_100g": 42.0,
        "sodium_mg_per_100g": 260.0,
        "aliases": "makhani dal, urad dal, black dal, butter dal, creamy dal, punjabi dal makhani",
    },
    {
        "dish_key": "chana_masala",
        "display_name": "Chana Masala (Chickpea Curry)",
        "category": "Curry",
        "default_serving_grams": 180.0,
        "calories_per_100g": 135.0,
        "protein_per_100g": 6.2,
        "carbs_per_100g": 18.4,
        "fat_per_100g": 4.5,
        "fiber_per_100g": 4.6,
        "iron_mg_per_100g": 2.2,
        "calcium_mg_per_100g": 38.0,
        "vitamin_c_mg_per_100g": 4.0,
        "vitamin_a_ug_per_100g": 22.0,
        "sodium_mg_per_100g": 280.0,
        "aliases": "chole, chana, chickpeas, kabuli chana, chole masala, punjabi chole",
    },
    {
        "dish_key": "rajma_chawal",
        "display_name": "Rajma Masala with Basmati Rice",
        "category": "Rice",
        "default_serving_grams": 300.0,
        "calories_per_100g": 130.0,
        "protein_per_100g": 4.8,
        "carbs_per_100g": 22.5,
        "fat_per_100g": 2.8,
        "fiber_per_100g": 3.2,
        "iron_mg_per_100g": 1.8,
        "calcium_mg_per_100g": 28.0,
        "vitamin_c_mg_per_100g": 2.2,
        "vitamin_a_ug_per_100g": 18.0,
        "sodium_mg_per_100g": 250.0,
        "aliases": "rajma, rajma chawal, kidney beans with rice, rajma curry, punjabi rajma",
    },
    {
        "dish_key": "sambar",
        "display_name": "South Indian Vegetable Sambar",
        "category": "Dal",
        "default_serving_grams": 150.0,
        "calories_per_100g": 72.0,
        "protein_per_100g": 3.1,
        "carbs_per_100g": 11.2,
        "fat_per_100g": 1.8,
        "fiber_per_100g": 2.6,
        "iron_mg_per_100g": 1.1,
        "calcium_mg_per_100g": 28.0,
        "vitamin_c_mg_per_100g": 5.8,
        "vitamin_a_ug_per_100g": 35.0,
        "sodium_mg_per_100g": 290.0,
        "aliases": "sambhar, south indian dal, lentil vegetable soup, tiffin sambar",
    },
    {
        "dish_key": "rasam",
        "display_name": "Tomato Pepper Rasam",
        "category": "Soup",
        "default_serving_grams": 150.0,
        "calories_per_100g": 45.0,
        "protein_per_100g": 1.2,
        "carbs_per_100g": 7.5,
        "fat_per_100g": 1.1,
        "fiber_per_100g": 1.2,
        "iron_mg_per_100g": 0.8,
        "calcium_mg_per_100g": 18.0,
        "vitamin_c_mg_per_100g": 8.5,
        "vitamin_a_ug_per_100g": 25.0,
        "sodium_mg_per_100g": 240.0,
        "aliases": "rasam, pepper rasam, tomato rasam, south indian rasam, saaru",
    },

    # --- INDIAN BREADS ---
    {
        "dish_key": "chapati_roti",
        "display_name": "Chapati / Phulka Roti",
        "category": "Bread",
        "default_serving_grams": 40.0,
        "calories_per_100g": 270.0,
        "protein_per_100g": 9.5,
        "carbs_per_100g": 52.0,
        "fat_per_100g": 2.8,
        "fiber_per_100g": 7.2,
        "iron_mg_per_100g": 3.8,
        "calcium_mg_per_100g": 30.0,
        "vitamin_c_mg_per_100g": 0.0,
        "vitamin_a_ug_per_100g": 0.0,
        "sodium_mg_per_100g": 110.0,
        "aliases": "roti, phulka, chapati, chapatti, whole wheat flatbread, rotis, 2 phulka rotis",
    },
    {
        "dish_key": "paratha_plain",
        "display_name": "Plain Layered Paratha",
        "category": "Bread",
        "default_serving_grams": 70.0,
        "calories_per_100g": 315.0,
        "protein_per_100g": 7.8,
        "carbs_per_100g": 46.0,
        "fat_per_100g": 12.0,
        "fiber_per_100g": 4.5,
        "iron_mg_per_100g": 2.8,
        "calcium_mg_per_100g": 28.0,
        "vitamin_c_mg_per_100g": 0.0,
        "vitamin_a_ug_per_100g": 25.0,
        "sodium_mg_per_100g": 210.0,
        "aliases": "plain paratha, tawa paratha, layered paratha, lachha paratha",
    },
    {
        "dish_key": "aloo_paratha",
        "display_name": "Aloo Paratha (Stuffed Potato Flatbread)",
        "category": "Bread",
        "default_serving_grams": 120.0,
        "calories_per_100g": 245.0,
        "protein_per_100g": 5.4,
        "carbs_per_100g": 38.0,
        "fat_per_100g": 8.5,
        "fiber_per_100g": 3.5,
        "iron_mg_per_100g": 2.2,
        "calcium_mg_per_100g": 26.0,
        "vitamin_c_mg_per_100g": 4.5,
        "vitamin_a_ug_per_100g": 12.0,
        "sodium_mg_per_100g": 290.0,
        "aliases": "paratha, alu paratha, potato paratha, stuffed paratha, aloo paratha with curd",
    },
    {
        "dish_key": "naan_plain",
        "display_name": "Plain Tandoori Naan",
        "category": "Bread",
        "default_serving_grams": 80.0,
        "calories_per_100g": 280.0,
        "protein_per_100g": 8.5,
        "carbs_per_100g": 52.0,
        "fat_per_100g": 4.5,
        "fiber_per_100g": 2.6,
        "iron_mg_per_100g": 2.0,
        "calcium_mg_per_100g": 35.0,
        "vitamin_c_mg_per_100g": 0.0,
        "vitamin_a_ug_per_100g": 0.0,
        "sodium_mg_per_100g": 280.0,
        "aliases": "naan, plain naan, tandoori roti, tandoori bread",
    },
    {
        "dish_key": "naan_butter",
        "display_name": "Butter Naan",
        "category": "Bread",
        "default_serving_grams": 80.0,
        "calories_per_100g": 310.0,
        "protein_per_100g": 8.2,
        "carbs_per_100g": 48.5,
        "fat_per_100g": 9.8,
        "fiber_per_100g": 2.4,
        "iron_mg_per_100g": 2.1,
        "calcium_mg_per_100g": 42.0,
        "vitamin_c_mg_per_100g": 0.0,
        "vitamin_a_ug_per_100g": 55.0,
        "sodium_mg_per_100g": 340.0,
        "aliases": "naan, butter naan, tandoori butter naan",
    },
    {
        "dish_key": "naan_garlic",
        "display_name": "Garlic Naan",
        "category": "Bread",
        "default_serving_grams": 85.0,
        "calories_per_100g": 315.0,
        "protein_per_100g": 8.4,
        "carbs_per_100g": 48.0,
        "fat_per_100g": 10.2,
        "fiber_per_100g": 2.5,
        "iron_mg_per_100g": 2.3,
        "calcium_mg_per_100g": 44.0,
        "vitamin_c_mg_per_100g": 1.2,
        "vitamin_a_ug_per_100g": 48.0,
        "sodium_mg_per_100g": 350.0,
        "aliases": "garlic naan, butter garlic naan, tandoori garlic naan",
    },
    {
        "dish_key": "poori",
        "display_name": "Poori (Puffed Fried Bread, 2 pcs)",
        "category": "Bread",
        "default_serving_grams": 60.0,
        "calories_per_100g": 340.0,
        "protein_per_100g": 7.2,
        "carbs_per_100g": 45.0,
        "fat_per_100g": 15.5,
        "fiber_per_100g": 3.8,
        "iron_mg_per_100g": 2.6,
        "calcium_mg_per_100g": 24.0,
        "vitamin_c_mg_per_100g": 0.0,
        "vitamin_a_ug_per_100g": 10.0,
        "sodium_mg_per_100g": 180.0,
        "aliases": "puri, poori, puri bhaji, fried puri, 2 pooris",
    },
    {
        "dish_key": "bhature",
        "display_name": "Bhature (Fried Leavened Bread)",
        "category": "Bread",
        "default_serving_grams": 90.0,
        "calories_per_100g": 360.0,
        "protein_per_100g": 7.8,
        "carbs_per_100g": 48.0,
        "fat_per_100g": 16.2,
        "fiber_per_100g": 2.1,
        "iron_mg_per_100g": 1.8,
        "calcium_mg_per_100g": 32.0,
        "vitamin_c_mg_per_100g": 0.0,
        "vitamin_a_ug_per_100g": 15.0,
        "sodium_mg_per_100g": 320.0,
        "aliases": "bhatura, chole bhature, bhature, fried bhatura",
    },

    # --- PANEER & VEGETABLE CURRIES ---
    {
        "dish_key": "paneer_butter_masala",
        "display_name": "Paneer Butter Masala",
        "category": "Curry",
        "default_serving_grams": 180.0,
        "calories_per_100g": 220.0,
        "protein_per_100g": 8.4,
        "carbs_per_100g": 9.5,
        "fat_per_100g": 17.2,
        "fiber_per_100g": 1.8,
        "iron_mg_per_100g": 1.3,
        "calcium_mg_per_100g": 160.0,
        "vitamin_c_mg_per_100g": 3.8,
        "vitamin_a_ug_per_100g": 85.0,
        "sodium_mg_per_100g": 310.0,
        "aliases": "paneer makhani, butter paneer, paneer makhani curry, paneer curry",
    },
    {
        "dish_key": "palak_paneer",
        "display_name": "Palak Paneer (Spinach Cottage Cheese)",
        "category": "Curry",
        "default_serving_grams": 180.0,
        "calories_per_100g": 165.0,
        "protein_per_100g": 8.8,
        "carbs_per_100g": 6.2,
        "fat_per_100g": 12.0,
        "fiber_per_100g": 2.9,
        "iron_mg_per_100g": 3.5,
        "calcium_mg_per_100g": 180.0,
        "vitamin_c_mg_per_100g": 12.0,
        "vitamin_a_ug_per_100g": 240.0,
        "sodium_mg_per_100g": 280.0,
        "aliases": "saag paneer, spinach paneer, palak paneer curry",
    },
    {
        "dish_key": "kadai_paneer",
        "display_name": "Kadai Paneer (Cottage Cheese with Bell Peppers)",
        "category": "Curry",
        "default_serving_grams": 180.0,
        "calories_per_100g": 195.0,
        "protein_per_100g": 9.2,
        "carbs_per_100g": 8.0,
        "fat_per_100g": 14.5,
        "fiber_per_100g": 2.2,
        "iron_mg_per_100g": 1.6,
        "calcium_mg_per_100g": 170.0,
        "vitamin_c_mg_per_100g": 14.0,
        "vitamin_a_ug_per_100g": 75.0,
        "sodium_mg_per_100g": 290.0,
        "aliases": "karahi paneer, capsicum paneer, spicy paneer curry",
    },
    {
        "dish_key": "shahi_paneer",
        "display_name": "Shahi Paneer (Royal Creamy Curry)",
        "category": "Curry",
        "default_serving_grams": 180.0,
        "calories_per_100g": 235.0,
        "protein_per_100g": 8.1,
        "carbs_per_100g": 11.0,
        "fat_per_100g": 18.5,
        "fiber_per_100g": 1.2,
        "iron_mg_per_100g": 1.2,
        "calcium_mg_per_100g": 165.0,
        "vitamin_c_mg_per_100g": 2.0,
        "vitamin_a_ug_per_100g": 90.0,
        "sodium_mg_per_100g": 300.0,
        "aliases": "shahi paneer, mughlai paneer, royal paneer, sweet creamy paneer",
    },
    {
        "dish_key": "paneer_tikka",
        "display_name": "Tandoori Paneer Tikka",
        "category": "Snack",
        "default_serving_grams": 150.0,
        "calories_per_100g": 210.0,
        "protein_per_100g": 12.5,
        "carbs_per_100g": 6.8,
        "fat_per_100g": 15.0,
        "fiber_per_100g": 1.5,
        "iron_mg_per_100g": 1.4,
        "calcium_mg_per_100g": 190.0,
        "vitamin_c_mg_per_100g": 6.5,
        "vitamin_a_ug_per_100g": 60.0,
        "sodium_mg_per_100g": 340.0,
        "aliases": "paneer tikka, tandoori paneer, grilled paneer, paneer starter",
    },
    {
        "dish_key": "aloo_gobi",
        "display_name": "Aloo Gobi (Potato Cauliflower Dry Curry)",
        "category": "Vegetable",
        "default_serving_grams": 150.0,
        "calories_per_100g": 110.0,
        "protein_per_100g": 2.8,
        "carbs_per_100g": 16.5,
        "fat_per_100g": 4.2,
        "fiber_per_100g": 3.2,
        "iron_mg_per_100g": 1.2,
        "calcium_mg_per_100g": 32.0,
        "vitamin_c_mg_per_100g": 24.0,
        "vitamin_a_ug_per_100g": 15.0,
        "sodium_mg_per_100g": 230.0,
        "aliases": "alu gobi, aloo gobhi, potato cauliflower, gobi sabzi",
    },
    {
        "dish_key": "aloo_matar",
        "display_name": "Aloo Matar (Potato Peas Curry)",
        "category": "Vegetable",
        "default_serving_grams": 160.0,
        "calories_per_100g": 118.0,
        "protein_per_100g": 3.4,
        "carbs_per_100g": 18.2,
        "fat_per_100g": 3.8,
        "fiber_per_100g": 3.5,
        "iron_mg_per_100g": 1.4,
        "calcium_mg_per_100g": 28.0,
        "vitamin_c_mg_per_100g": 15.0,
        "vitamin_a_ug_per_100g": 30.0,
        "sodium_mg_per_100g": 240.0,
        "aliases": "alu matar, potato peas, aloo mutter curry, aloo mutter",
    },
    {
        "dish_key": "bhindi_masala",
        "display_name": "Bhindi Masala (Spiced Okra Fry)",
        "category": "Vegetable",
        "default_serving_grams": 140.0,
        "calories_per_100g": 115.0,
        "protein_per_100g": 2.4,
        "carbs_per_100g": 12.8,
        "fat_per_100g": 6.5,
        "fiber_per_100g": 3.8,
        "iron_mg_per_100g": 1.5,
        "calcium_mg_per_100g": 72.0,
        "vitamin_c_mg_per_100g": 18.0,
        "vitamin_a_ug_per_100g": 45.0,
        "sodium_mg_per_100g": 210.0,
        "aliases": "bhindi, okra, lady finger, bhindi fry, okra fry, bhindi sabzi",
    },
    {
        "dish_key": "baingan_bharta",
        "display_name": "Baingan Bharta (Smoked Eggplant)",
        "category": "Vegetable",
        "default_serving_grams": 150.0,
        "calories_per_100g": 95.0,
        "protein_per_100g": 2.1,
        "carbs_per_100g": 10.5,
        "fat_per_100g": 5.2,
        "fiber_per_100g": 3.6,
        "iron_mg_per_100g": 1.2,
        "calcium_mg_per_100g": 30.0,
        "vitamin_c_mg_per_100g": 8.0,
        "vitamin_a_ug_per_100g": 20.0,
        "sodium_mg_per_100g": 220.0,
        "aliases": "eggplant mash, roasted brinjal, baingan bhurtha, aubergine bharta",
    },
    {
        "dish_key": "kofta",
        "display_name": "Malai Kofta (Paneer-Potato Dumplings in Curry)",
        "category": "Curry",
        "default_serving_grams": 180.0,
        "calories_per_100g": 240.0,
        "protein_per_100g": 5.5,
        "carbs_per_100g": 16.0,
        "fat_per_100g": 17.5,
        "fiber_per_100g": 1.8,
        "iron_mg_per_100g": 1.3,
        "calcium_mg_per_100g": 95.0,
        "vitamin_c_mg_per_100g": 3.0,
        "vitamin_a_ug_per_100g": 65.0,
        "sodium_mg_per_100g": 310.0,
        "aliases": "malai kofta, kofta curry, veg kofta, creamy kofta",
    },

    # --- POULTRY & NON-VEG ---
    {
        "dish_key": "butter_chicken",
        "display_name": "Butter Chicken (Murgh Makhani)",
        "category": "Curry",
        "default_serving_grams": 200.0,
        "calories_per_100g": 195.0,
        "protein_per_100g": 14.5,
        "carbs_per_100g": 6.2,
        "fat_per_100g": 12.8,
        "fiber_per_100g": 1.1,
        "iron_mg_per_100g": 1.6,
        "calcium_mg_per_100g": 42.0,
        "vitamin_c_mg_per_100g": 3.2,
        "vitamin_a_ug_per_100g": 65.0,
        "sodium_mg_per_100g": 320.0,
        "aliases": "murgh makhani, chicken makhani, creamy chicken, indian butter chicken",
    },
    {
        "dish_key": "chicken_curry",
        "display_name": "Home-style Indian Chicken Curry",
        "category": "Curry",
        "default_serving_grams": 200.0,
        "calories_per_100g": 160.0,
        "protein_per_100g": 16.2,
        "carbs_per_100g": 4.5,
        "fat_per_100g": 8.8,
        "fiber_per_100g": 1.2,
        "iron_mg_per_100g": 1.8,
        "calcium_mg_per_100g": 26.0,
        "vitamin_c_mg_per_100g": 4.5,
        "vitamin_a_ug_per_100g": 25.0,
        "sodium_mg_per_100g": 290.0,
        "aliases": "tari wala chicken, chicken gravy, desi chicken curry, chicken masala",
    },
    {
        "dish_key": "chicken_tikka",
        "display_name": "Tandoori Chicken Tikka",
        "category": "Snack",
        "default_serving_grams": 150.0,
        "calories_per_100g": 175.0,
        "protein_per_100g": 24.5,
        "carbs_per_100g": 3.2,
        "fat_per_100g": 7.0,
        "fiber_per_100g": 0.8,
        "iron_mg_per_100g": 1.9,
        "calcium_mg_per_100g": 35.0,
        "vitamin_c_mg_per_100g": 2.8,
        "vitamin_a_ug_per_100g": 18.0,
        "sodium_mg_per_100g": 360.0,
        "aliases": "tandoori chicken, grilled chicken tikka, chicken kabab, chicken starter",
    },

    # --- RICE & SOUTH INDIAN BREAKFAST ---
    {
        "dish_key": "biryani_chicken",
        "display_name": "Chicken Dum Biryani",
        "category": "Rice",
        "default_serving_grams": 300.0,
        "calories_per_100g": 175.0,
        "protein_per_100g": 8.5,
        "carbs_per_100g": 23.5,
        "fat_per_100g": 5.8,
        "fiber_per_100g": 1.6,
        "iron_mg_per_100g": 1.4,
        "calcium_mg_per_100g": 22.0,
        "vitamin_c_mg_per_100g": 1.5,
        "vitamin_a_ug_per_100g": 18.0,
        "sodium_mg_per_100g": 280.0,
        "aliases": "biryani, hyderabadi biryani, chicken biryani, dum biryani",
    },
    {
        "dish_key": "biryani_veg",
        "display_name": "Vegetable Biryani / Pulao",
        "category": "Rice",
        "default_serving_grams": 280.0,
        "calories_per_100g": 145.0,
        "protein_per_100g": 3.8,
        "carbs_per_100g": 25.0,
        "fat_per_100g": 3.5,
        "fiber_per_100g": 2.4,
        "iron_mg_per_100g": 1.1,
        "calcium_mg_per_100g": 28.0,
        "vitamin_c_mg_per_100g": 3.5,
        "vitamin_a_ug_per_100g": 30.0,
        "sodium_mg_per_100g": 250.0,
        "aliases": "veg biryani, veg pulao, peas pulao, vegetable rice",
    },
    {
        "dish_key": "khichdi",
        "display_name": "Moong Dal Khichdi",
        "category": "Rice",
        "default_serving_grams": 220.0,
        "calories_per_100g": 120.0,
        "protein_per_100g": 4.8,
        "carbs_per_100g": 21.0,
        "fat_per_100g": 2.2,
        "fiber_per_100g": 2.5,
        "iron_mg_per_100g": 1.3,
        "calcium_mg_per_100g": 20.0,
        "vitamin_c_mg_per_100g": 1.0,
        "vitamin_a_ug_per_100g": 12.0,
        "sodium_mg_per_100g": 210.0,
        "aliases": "khichadi, dal khichdi, moong khichdi, comfort rice",
    },
    {
        "dish_key": "idli",
        "display_name": "Idli (Steamed Rice-Lentil Cake, 2 pcs)",
        "category": "Breakfast",
        "default_serving_grams": 100.0,
        "calories_per_100g": 132.0,
        "protein_per_100g": 4.2,
        "carbs_per_100g": 26.5,
        "fat_per_100g": 0.8,
        "fiber_per_100g": 1.8,
        "iron_mg_per_100g": 0.9,
        "calcium_mg_per_100g": 18.0,
        "vitamin_c_mg_per_100g": 0.0,
        "vitamin_a_ug_per_100g": 0.0,
        "sodium_mg_per_100g": 160.0,
        "aliases": "idlis, steamed idli, rice cake, south indian idli, 2 idlis",
    },
    {
        "dish_key": "dosa_plain",
        "display_name": "Plain Dosa (Crisp Rice-Lentil Crepe)",
        "category": "Breakfast",
        "default_serving_grams": 120.0,
        "calories_per_100g": 165.0,
        "protein_per_100g": 4.1,
        "carbs_per_100g": 28.0,
        "fat_per_100g": 4.2,
        "fiber_per_100g": 1.9,
        "iron_mg_per_100g": 1.2,
        "calcium_mg_per_100g": 22.0,
        "vitamin_c_mg_per_100g": 0.0,
        "vitamin_a_ug_per_100g": 0.0,
        "sodium_mg_per_100g": 210.0,
        "aliases": "plain dosa, roast dosa, sada dosa, crispy dosa",
    },
    {
        "dish_key": "dosa_masala",
        "display_name": "Masala Dosa (with Potato Filling)",
        "category": "Breakfast",
        "default_serving_grams": 180.0,
        "calories_per_100g": 190.0,
        "protein_per_100g": 4.6,
        "carbs_per_100g": 29.5,
        "fat_per_100g": 6.2,
        "fiber_per_100g": 2.6,
        "iron_mg_per_100g": 1.6,
        "calcium_mg_per_100g": 25.0,
        "vitamin_c_mg_per_100g": 3.2,
        "vitamin_a_ug_per_100g": 10.0,
        "sodium_mg_per_100g": 270.0,
        "aliases": "dosa, masala dosa, mysore masala dosa, aloo dosa",
    },
    {
        "dish_key": "medu_vada",
        "display_name": "Medu Vada (Crispy Lentil Doughnut)",
        "category": "Breakfast",
        "default_serving_grams": 70.0,
        "calories_per_100g": 275.0,
        "protein_per_100g": 7.5,
        "carbs_per_100g": 26.0,
        "fat_per_100g": 15.8,
        "fiber_per_100g": 3.2,
        "iron_mg_per_100g": 2.1,
        "calcium_mg_per_100g": 40.0,
        "vitamin_c_mg_per_100g": 1.0,
        "vitamin_a_ug_per_100g": 10.0,
        "sodium_mg_per_100g": 280.0,
        "aliases": "vada, medu vada, uddina vade, south indian vada, fried vada",
    },
    {
        "dish_key": "uttapam",
        "display_name": "Onion Tomato Uttapam",
        "category": "Breakfast",
        "default_serving_grams": 160.0,
        "calories_per_100g": 170.0,
        "protein_per_100g": 4.4,
        "carbs_per_100g": 27.5,
        "fat_per_100g": 5.0,
        "fiber_per_100g": 2.4,
        "iron_mg_per_100g": 1.4,
        "calcium_mg_per_100g": 28.0,
        "vitamin_c_mg_per_100g": 6.5,
        "vitamin_a_ug_per_100g": 25.0,
        "sodium_mg_per_100g": 250.0,
        "aliases": "uttapam, onion uttapam, tomato uttapam, vegetable uttapam",
    },
    {
        "dish_key": "poha",
        "display_name": "Kanda Poha (Flattened Rice with Peanuts)",
        "category": "Breakfast",
        "default_serving_grams": 150.0,
        "calories_per_100g": 165.0,
        "protein_per_100g": 3.8,
        "carbs_per_100g": 28.0,
        "fat_per_100g": 4.5,
        "fiber_per_100g": 2.2,
        "iron_mg_per_100g": 3.2,
        "calcium_mg_per_100g": 22.0,
        "vitamin_c_mg_per_100g": 8.5,
        "vitamin_a_ug_per_100g": 15.0,
        "sodium_mg_per_100g": 230.0,
        "aliases": "pohe, batata poha, flattened rice, chivda, kanda poha",
    },
    {
        "dish_key": "upma",
        "display_name": "Rava Upma (Semolina Savory Porridge)",
        "category": "Breakfast",
        "default_serving_grams": 160.0,
        "calories_per_100g": 150.0,
        "protein_per_100g": 3.5,
        "carbs_per_100g": 25.5,
        "fat_per_100g": 4.0,
        "fiber_per_100g": 1.8,
        "iron_mg_per_100g": 1.5,
        "calcium_mg_per_100g": 20.0,
        "vitamin_c_mg_per_100g": 4.0,
        "vitamin_a_ug_per_100g": 18.0,
        "sodium_mg_per_100g": 220.0,
        "aliases": "upma, rava upma, sooji upma, semolina breakfast",
    },
    {
        "dish_key": "dhokla",
        "display_name": "Khaman Dhokla (Steamed Gram Cake)",
        "category": "Breakfast",
        "default_serving_grams": 120.0,
        "calories_per_100g": 160.0,
        "protein_per_100g": 6.8,
        "carbs_per_100g": 24.0,
        "fat_per_100g": 4.2,
        "fiber_per_100g": 3.0,
        "iron_mg_per_100g": 1.8,
        "calcium_mg_per_100g": 35.0,
        "vitamin_c_mg_per_100g": 3.5,
        "vitamin_a_ug_per_100g": 15.0,
        "sodium_mg_per_100g": 380.0,
        "aliases": "khaman, dhokla, gujarati dhokla, steamed besan cake",
    },

    # --- SNACKS & STREET FOOD ---
    {
        "dish_key": "samosa",
        "display_name": "Punjabi Samosa (Potato-Pea Stuffed)",
        "category": "Snack",
        "default_serving_grams": 80.0,
        "calories_per_100g": 260.0,
        "protein_per_100g": 4.5,
        "carbs_per_100g": 32.0,
        "fat_per_100g": 13.0,
        "fiber_per_100g": 2.8,
        "iron_mg_per_100g": 1.5,
        "calcium_mg_per_100g": 20.0,
        "vitamin_c_mg_per_100g": 4.2,
        "vitamin_a_ug_per_100g": 8.0,
        "sodium_mg_per_100g": 320.0,
        "aliases": "samosas, potato samosa, fried samosa, punjabi samosa",
    },
    {
        "dish_key": "pav_bhaji",
        "display_name": "Pav Bhaji (Spiced Mash with Buttered Buns)",
        "category": "Snack",
        "default_serving_grams": 250.0,
        "calories_per_100g": 175.0,
        "protein_per_100g": 4.2,
        "carbs_per_100g": 24.5,
        "fat_per_100g": 7.0,
        "fiber_per_100g": 3.6,
        "iron_mg_per_100g": 2.0,
        "calcium_mg_per_100g": 45.0,
        "vitamin_c_mg_per_100g": 14.0,
        "vitamin_a_ug_per_100g": 55.0,
        "sodium_mg_per_100g": 360.0,
        "aliases": "bhaji pav, bombay pav bhaji, butter pav bhaji, pav bhaji",
    },
    {
        "dish_key": "vada_pav",
        "display_name": "Mumbai Vada Pav",
        "category": "Snack",
        "default_serving_grams": 130.0,
        "calories_per_100g": 240.0,
        "protein_per_100g": 5.2,
        "carbs_per_100g": 34.0,
        "fat_per_100g": 9.5,
        "fiber_per_100g": 2.5,
        "iron_mg_per_100g": 1.8,
        "calcium_mg_per_100g": 32.0,
        "vitamin_c_mg_per_100g": 5.0,
        "vitamin_a_ug_per_100g": 15.0,
        "sodium_mg_per_100g": 350.0,
        "aliases": "wada pav, bombay burger, batata vada pav, vada pav",
    },
    {
        "dish_key": "pani_puri",
        "display_name": "Pani Puri / Golgappe (6 pcs)",
        "category": "Snack",
        "default_serving_grams": 150.0,
        "calories_per_100g": 140.0,
        "protein_per_100g": 2.8,
        "carbs_per_100g": 26.0,
        "fat_per_100g": 3.0,
        "fiber_per_100g": 2.2,
        "iron_mg_per_100g": 2.0,
        "calcium_mg_per_100g": 25.0,
        "vitamin_c_mg_per_100g": 8.0,
        "vitamin_a_ug_per_100g": 20.0,
        "sodium_mg_per_100g": 420.0,
        "aliases": "golgappa, puchka, pani batasha, gupchup, pani puri",
    },
    {
        "dish_key": "aloo_tikki",
        "display_name": "Aloo Tikki (Crispy Potato Cutlet)",
        "category": "Snack",
        "default_serving_grams": 100.0,
        "calories_per_100g": 225.0,
        "protein_per_100g": 3.6,
        "carbs_per_100g": 28.5,
        "fat_per_100g": 11.0,
        "fiber_per_100g": 2.6,
        "iron_mg_per_100g": 1.4,
        "calcium_mg_per_100g": 22.0,
        "vitamin_c_mg_per_100g": 6.5,
        "vitamin_a_ug_per_100g": 10.0,
        "sodium_mg_per_100g": 310.0,
        "aliases": "alu tikki, potato cutlet, aloo chaat, potato patty",
    },
    {
        "dish_key": "vegetable_pakora",
        "display_name": "Mixed Vegetable Pakora / Fritters",
        "category": "Snack",
        "default_serving_grams": 100.0,
        "calories_per_100g": 270.0,
        "protein_per_100g": 6.2,
        "carbs_per_100g": 28.0,
        "fat_per_100g": 15.0,
        "fiber_per_100g": 3.5,
        "iron_mg_per_100g": 1.9,
        "calcium_mg_per_100g": 45.0,
        "vitamin_c_mg_per_100g": 8.0,
        "vitamin_a_ug_per_100g": 35.0,
        "sodium_mg_per_100g": 340.0,
        "aliases": "pakoda, veg pakora, onion bhaji, pakode, vegetable fritters",
    },

    # --- SWEETS & DESSERTS ---
    {
        "dish_key": "gulab_jamun",
        "display_name": "Gulab Jamun (Milk Solid Sweet, 2 pcs)",
        "category": "Sweet",
        "default_serving_grams": 70.0,
        "calories_per_100g": 330.0,
        "protein_per_100g": 4.2,
        "carbs_per_100g": 56.0,
        "fat_per_100g": 10.5,
        "fiber_per_100g": 0.4,
        "iron_mg_per_100g": 0.6,
        "calcium_mg_per_100g": 80.0,
        "vitamin_c_mg_per_100g": 0.0,
        "vitamin_a_ug_per_100g": 25.0,
        "sodium_mg_per_100g": 90.0,
        "aliases": "jamun, indian sweet, gulab jamuns, mawa gulab jamun",
    },
    {
        "dish_key": "rasgulla",
        "display_name": "Rasgulla (Syrupy Cottage Cheese Balls)",
        "category": "Sweet",
        "default_serving_grams": 80.0,
        "calories_per_100g": 185.0,
        "protein_per_100g": 4.0,
        "carbs_per_100g": 38.0,
        "fat_per_100g": 1.8,
        "fiber_per_100g": 0.0,
        "iron_mg_per_100g": 0.3,
        "calcium_mg_per_100g": 95.0,
        "vitamin_c_mg_per_100g": 0.0,
        "vitamin_a_ug_per_100g": 15.0,
        "sodium_mg_per_100g": 60.0,
        "aliases": "rosogolla, bengali rasgulla, white sweet, chhena rasgulla",
    },
    {
        "dish_key": "kheer",
        "display_name": "Rice Kheer (Cardamom Rice Pudding)",
        "category": "Sweet",
        "default_serving_grams": 150.0,
        "calories_per_100g": 155.0,
        "protein_per_100g": 4.5,
        "carbs_per_100g": 24.0,
        "fat_per_100g": 4.8,
        "fiber_per_100g": 0.5,
        "iron_mg_per_100g": 0.4,
        "calcium_mg_per_100g": 120.0,
        "vitamin_c_mg_per_100g": 0.5,
        "vitamin_a_ug_per_100g": 35.0,
        "sodium_mg_per_100g": 65.0,
        "aliases": "payasam, rice payasam, chawal ki kheer, rice pudding",
    },
    {
        "dish_key": "kaju_katli",
        "display_name": "Kaju Katli (Cashew Diamond Fudge)",
        "category": "Sweet",
        "default_serving_grams": 50.0,
        "calories_per_100g": 440.0,
        "protein_per_100g": 9.5,
        "carbs_per_100g": 54.0,
        "fat_per_100g": 21.0,
        "fiber_per_100g": 1.8,
        "iron_mg_per_100g": 2.4,
        "calcium_mg_per_100g": 45.0,
        "vitamin_c_mg_per_100g": 0.0,
        "vitamin_a_ug_per_100g": 10.0,
        "sodium_mg_per_100g": 40.0,
        "aliases": "kaju barfi, cashew fudge, kaju katli sweet",
    },
    {
        "dish_key": "laddu",
        "display_name": "Besan Laddu",
        "category": "Sweet",
        "default_serving_grams": 50.0,
        "calories_per_100g": 460.0,
        "protein_per_100g": 8.0,
        "carbs_per_100g": 52.0,
        "fat_per_100g": 24.5,
        "fiber_per_100g": 3.2,
        "iron_mg_per_100g": 2.2,
        "calcium_mg_per_100g": 35.0,
        "vitamin_c_mg_per_100g": 0.0,
        "vitamin_a_ug_per_100g": 30.0,
        "sodium_mg_per_100g": 50.0,
        "aliases": "ladoo, besan ladoo, motichoor laddu, sweet ball",
    },
    {
        "dish_key": "jalebi",
        "display_name": "Jalebi (Crisp Sugar Syrup Swirls)",
        "category": "Sweet",
        "default_serving_grams": 60.0,
        "calories_per_100g": 380.0,
        "protein_per_100g": 2.5,
        "carbs_per_100g": 72.0,
        "fat_per_100g": 9.5,
        "fiber_per_100g": 0.2,
        "iron_mg_per_100g": 0.5,
        "calcium_mg_per_100g": 15.0,
        "vitamin_c_mg_per_100g": 0.0,
        "vitamin_a_ug_per_100g": 10.0,
        "sodium_mg_per_100g": 60.0,
        "aliases": "jilapi, crisp jalebi, sugar jalebi, indian spiral sweet",
    },
]


async def seed_ifct_database() -> int:
    """Seeds the database with authentic IFCT Indian recipe nutrition profiles."""
    await init_db()

    async with AsyncSessionLocal() as session:
        inserted_count = 0
        for dish_data in SEEDED_INDIAN_DISHES:
            # Check if dish key already exists
            query = select(DishNutritionProfile).where(DishNutritionProfile.dish_key == dish_data["dish_key"])
            result = await session.execute(query)
            existing = result.scalar_one_or_none()

            if not existing:
                profile = DishNutritionProfile(**dish_data)
                session.add(profile)
                inserted_count += 1
            else:
                # Update existing
                for k, v in dish_data.items():
                    setattr(existing, k, v)

        await session.commit()
        logger.info(f"Seeded/Updated {len(SEEDED_INDIAN_DISHES)} Indian dish nutrition profiles into database.")
        return inserted_count


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    asyncio.run(seed_ifct_database())
